CREATE TABLE IF NOT EXISTS schema_migrations (
  version VARCHAR(128) PRIMARY KEY,
  applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source VARCHAR(64) NOT NULL,
  location VARCHAR(255) NOT NULL,
  location_slug VARCHAR(128) NOT NULL,
  run_date DATE NOT NULL,
  snapshot_file VARCHAR(512) NULL,
  report_file VARCHAR(512) NULL,
  previous_snapshot VARCHAR(512) NULL,
  resume_path VARCHAR(1024) NULL,
  baseline_created BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL DEFAULT 'imported',
  current_job_count INT NOT NULL DEFAULT 0,
  added_count INT NOT NULL DEFAULT 0,
  canceled_count INT NOT NULL DEFAULT 0,
  ranked_job_count INT NOT NULL DEFAULT 0,
  backlog_count INT NOT NULL DEFAULT 0,
  deferred_score_count INT NOT NULL DEFAULT 0,
  score_error_count INT NOT NULL DEFAULT 0,
  profile_highlights JSON NULL,
  fit_summary JSON NULL,
  scored_dates JSON NULL,
  deferred_dates JSON NULL,
  raw_report JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_runs_source_location_date (source, location_slug, run_date),
  KEY idx_runs_date (run_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS jobs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  source VARCHAR(64) NOT NULL,
  job_key VARCHAR(255) NOT NULL,
  external_id VARCHAR(64) NULL,
  jr VARCHAR(64) NULL,
  title VARCHAR(512) NULL,
  link VARCHAR(1024) NULL,
  department VARCHAR(255) NULL,
  first_seen_date DATE NULL,
  last_seen_date DATE NULL,
  latest_content_hash CHAR(64) NULL,
  latest_seen_run_id BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_jobs_source_key (source, job_key),
  KEY idx_jobs_jr (jr),
  KEY idx_jobs_external_id (external_id),
  KEY idx_jobs_last_seen (last_seen_date),
  CONSTRAINT fk_jobs_latest_run FOREIGN KEY (latest_seen_run_id) REFERENCES runs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS job_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  job_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(64) NOT NULL,
  job_key VARCHAR(255) NOT NULL,
  title VARCHAR(512) NULL,
  jr VARCHAR(64) NULL,
  external_id VARCHAR(64) NULL,
  link VARCHAR(1024) NULL,
  locations JSON NULL,
  department VARCHAR(255) NULL,
  work_location_option VARCHAR(64) NULL,
  posted_ts BIGINT NULL,
  creation_ts BIGINT NULL,
  date_posted DATETIME NULL,
  valid_through DATETIME NULL,
  employment_type VARCHAR(64) NULL,
  description MEDIUMTEXT NULL,
  summary MEDIUMTEXT NULL,
  responsibilities JSON NULL,
  requirements_json JSON NULL,
  preferred JSON NULL,
  detail_error TEXT NULL,
  content_hash CHAR(64) NOT NULL,
  raw_json JSON NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_job_snapshots_run_job (run_id, job_id),
  KEY idx_job_snapshots_job (job_id),
  KEY idx_job_snapshots_hash (content_hash),
  CONSTRAINT fk_job_snapshots_run FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_job_snapshots_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  job_id BIGINT UNSIGNED NOT NULL,
  score TINYINT UNSIGNED NULL,
  suitability VARCHAR(64) NULL,
  recommendation VARCHAR(64) NULL,
  matched_reasons JSON NULL,
  gap_reasons JSON NULL,
  verdict MEDIUMTEXT NULL,
  first_seen_date DATE NULL,
  skipped_reason VARCHAR(64) NULL,
  error TEXT NULL,
  profile_hash VARCHAR(64) NULL,
  resume_path VARCHAR(1024) NULL,
  raw_score JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_scores_run_job (run_id, job_id),
  KEY idx_scores_job (job_id),
  KEY idx_scores_score (score),
  KEY idx_scores_suitability (suitability),
  CONSTRAINT chk_scores_range CHECK (score IS NULL OR score <= 100),
  CONSTRAINT fk_scores_run FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_scores_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resume_scores (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id BIGINT UNSIGNED NOT NULL,
  source VARCHAR(64) NOT NULL,
  profile_hash VARCHAR(64) NOT NULL,
  resume_path VARCHAR(1024) NULL,
  score TINYINT UNSIGNED NOT NULL,
  suitability VARCHAR(64) NULL,
  recommendation VARCHAR(64) NULL,
  matched_reasons JSON NULL,
  gap_reasons JSON NULL,
  verdict MEDIUMTEXT NULL,
  first_seen_date DATE NULL,
  matched_keywords JSON NULL,
  selection_reasons JSON NULL,
  report_file VARCHAR(512) NULL,
  raw_score JSON NOT NULL,
  scored_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_resume_scores_profile_job (profile_hash, job_id),
  KEY idx_resume_scores_job (job_id),
  KEY idx_resume_scores_source_score (source, score),
  CONSTRAINT chk_resume_scores_range CHECK (score <= 100),
  CONSTRAINT fk_resume_scores_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cancellations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id BIGINT UNSIGNED NOT NULL,
  job_id BIGINT UNSIGNED NULL,
  source VARCHAR(64) NOT NULL,
  location_slug VARCHAR(128) NOT NULL,
  canceled_key CHAR(64) NOT NULL,
  jr VARCHAR(64) NULL,
  title VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_cancellations_run_key (run_id, canceled_key),
  KEY idx_cancellations_jr (jr),
  CONSTRAINT fk_cancellations_run FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
  CONSTRAINT fk_cancellations_job FOREIGN KEY (job_id) REFERENCES jobs(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO schema_migrations (version)
VALUES ('001_mysql_persistence')
ON DUPLICATE KEY UPDATE applied_at = applied_at;
